"i18n.shared.create_allow_action_message.1000": "No authorization to access the resource.",
"i18n.shared.create_allow_action_message.1000.channel": "No authorization to access the resource.",
"i18n.shared.create_allow_action_message.1000.concept": "No authorization to access the resource.",
"i18n.shared.create_allow_action_message.1000.dataservice": "No authorization to access the resource.",
"i18n.shared.create_allow_action_message.1000.dataset": "No authorization to access the resource.",
"i18n.shared.create_allow_action_message.1000.dcat_catalog_record": "No authorization to access the resource.",
"i18n.shared.create_allow_action_message.1000.distribution": "No authorization to access the resource.",
"i18n.shared.create_allow_action_message.1000.publicservice": "No authorization to access the resource.",
"i18n.shared.create_allow_action_message.1001": "The resource is forbidden.",
"i18n.shared.create_allow_action_message.1001.channel": "The resource is forbidden.",
"i18n.shared.create_allow_action_message.1001.concept": "The resource is forbidden.",
"i18n.shared.create_allow_action_message.1001.dataservice": "The resource is forbidden.",
"i18n.shared.create_allow_action_message.1001.dataset": "The resource is forbidden.",
"i18n.shared.create_allow_action_message.1001.dcat_catalog_record": "Non siete autorizzati. Si prega di verificare con il Local Data Steward.",
"i18n.shared.create_allow_action_message.1001.distribution": "The resource is forbidden.",
"i18n.shared.create_allow_action_message.1001.publicservice": "The resource is forbidden.",
"i18n.shared.create_allow_action_message.2000.channel": "No resource has been found.",
"i18n.shared.create_allow_action_message.2000.distribution": "No resource has been found.",
"i18n.shared.create_allow_action_message.2003.channel": "The resource is locked.",
"i18n.shared.create_allow_action_message.2003.distribution": "The resource is locked.",

"i18n.shared.delete_allow_action_message.1000": "No authorization to access the resource.",
"i18n.shared.delete_allow_action_message.1000.channel": "No authorization to access the resource.",
"i18n.shared.delete_allow_action_message.1000.concept": "No authorization to access the resource.",
"i18n.shared.delete_allow_action_message.1000.dataservice": "No authorization to access the resource.",
"i18n.shared.delete_allow_action_message.1000.dataset": "No authorization to access the resource.",
"i18n.shared.delete_allow_action_message.1000.dcat_catalog_record": "No authorization to access the resource.",
"i18n.shared.delete_allow_action_message.1000.distribution": "No authorization to access the resource.",
"i18n.shared.delete_allow_action_message.1000.publicservice": "No authorization to access the resource.",
"i18n.shared.delete_allow_action_message.1001": "The resource is forbidden.",
"i18n.shared.delete_allow_action_message.1001.channel": "The resource is forbidden.",
"i18n.shared.delete_allow_action_message.1001.concept": "The resource is forbidden.",
"i18n.shared.delete_allow_action_message.1001.dataservice": "The resource is forbidden.",
"i18n.shared.delete_allow_action_message.1001.dataset": "The resource is forbidden.",
"i18n.shared.delete_allow_action_message.1001.dcat_catalog_record": "The resource is forbidden.",
"i18n.shared.delete_allow_action_message.1001.distribution": "The resource is forbidden.",
"i18n.shared.delete_allow_action_message.1001.publicservice": "The resource is forbidden.",
"i18n.shared.delete_allow_action_message.2000": "No resource has been found.",
"i18n.shared.delete_allow_action_message.2000.channel": "No resource has been found.",
"i18n.shared.delete_allow_action_message.2000.concept": "No resource has been found.",
"i18n.shared.delete_allow_action_message.2000.dataservice": "No resource has been found.",
"i18n.shared.delete_allow_action_message.2000.dataset": "No resource has been found.",
"i18n.shared.delete_allow_action_message.2000.dcat_catalog_record": "No resource has been found.",
"i18n.shared.delete_allow_action_message.2000.distribution": "No resource has been found.",
"i18n.shared.delete_allow_action_message.2000.publicservice": "No resource has been found.",
"i18n.shared.delete_allow_action_message.2001": "The resource cannot be deleted. It is referenced from other resources.",
"i18n.shared.delete_allow_action_message.2001.concept": "Questo concetto non può essere eliminato perché è utilizzato in uno o più elementi di dati. Rimuovere gli elementi di dati per eliminare il concetto.",
"i18n.shared.delete_allow_action_message.2001.dataservice": "Questo API non può essere eliminato perché una o più distributions vi fanno riferimento",
"i18n.shared.delete_allow_action_message.2001.dataset": "The resource cannot be deleted. It is referenced from other resources.",
"i18n.shared.delete_allow_action_message.2001.publicservice": "The resource cannot be deleted. It is referenced from other resources.",
"i18n.shared.delete_allow_action_message.2002": "The resource cannot be deleted. It is referenced as a previous version.",
"i18n.shared.delete_allow_action_message.2002.concept": "The resource cannot be deleted. It is referenced as a previous version.",
"i18n.shared.delete_allow_action_message.2002.dataservice": "Questo API non può essere eliminato perché esiste una versione successiva.",
"i18n.shared.delete_allow_action_message.2002.dataset": "The resource cannot be deleted. It is referenced as a previous version.",
"i18n.shared.delete_allow_action_message.2002.publicservice": "The resource cannot be deleted. It is referenced as a previous version.",
"i18n.shared.delete_allow_action_message.2003": "The resource is locked.",
"i18n.shared.delete_allow_action_message.2003.channel": "The resource is locked.",
"i18n.shared.delete_allow_action_message.2003.concept": "The resource is locked.",
"i18n.shared.delete_allow_action_message.2003.dataservice": "The resource is locked.",
"i18n.shared.delete_allow_action_message.2003.dataset": "The resource is locked.",
"i18n.shared.delete_allow_action_message.2003.dcat_catalog_record": "The resource is locked.",
"i18n.shared.delete_allow_action_message.2003.distribution": "The resource is locked.",
"i18n.shared.delete_allow_action_message.2003.publicservice": "The resource is locked.",
"i18n.shared.delete_allow_action_message.2004": "The resource cannot be deleted. The publication level must be 'Internal'.",
"i18n.shared.delete_allow_action_message.2004.concept": "Questo concetto non può essere cancellato perché è già stato reso pubblico.",
"i18n.shared.delete_allow_action_message.2004.dataservice": "Questo API non può essere eliminato perché il suo livello di pubblicazione è impostato su I14Y.",
"i18n.shared.delete_allow_action_message.2004.dataset": "The resource cannot be deleted. The publication level must be 'Internal'.",
"i18n.shared.delete_allow_action_message.2004.publicservice": "The resource cannot be deleted. The publication level must be 'Internal'.",

"i18n.shared.edit_allow_action_message.1000": "No authorization to access the resource.",
"i18n.shared.edit_allow_action_message.1000.channel": "No authorization to access the resource.",
"i18n.shared.edit_allow_action_message.1000.concept": "No authorization to access the resource.",
"i18n.shared.edit_allow_action_message.1000.dataservice": "No authorization to access the resource.",
"i18n.shared.edit_allow_action_message.1000.dataset": "No authorization to access the resource.",
"i18n.shared.edit_allow_action_message.1000.dcat_catalog_record": "No authorization to access the resource.",
"i18n.shared.edit_allow_action_message.1000.distribution": "No authorization to access the resource.",
"i18n.shared.edit_allow_action_message.1000.publicservice": "No authorization to access the resource.",
"i18n.shared.edit_allow_action_message.1001": "The resource is forbidden.",
"i18n.shared.edit_allow_action_message.1001.channel": "The resource is forbidden.",
"i18n.shared.edit_allow_action_message.1001.concept": "The resource is forbidden.",
"i18n.shared.edit_allow_action_message.1001.dataservice": "The resource is forbidden.",
"i18n.shared.edit_allow_action_message.1001.dataset": "The resource is forbidden.",
"i18n.shared.edit_allow_action_message.1001.dcat_catalog_record": "The resource is forbidden.",
"i18n.shared.edit_allow_action_message.1001.distribution": "The resource is forbidden.",
"i18n.shared.edit_allow_action_message.1001.publicservice": "The resource is forbidden.",
"i18n.shared.edit_allow_action_message.2000": "No resource has been found.",
"i18n.shared.edit_allow_action_message.2000.channel": "No resource has been found.",
"i18n.shared.edit_allow_action_message.2000.concept": "No resource has been found.",
"i18n.shared.edit_allow_action_message.2000.dataservice": "No resource has been found.",
"i18n.shared.edit_allow_action_message.2000.dataset": "No resource has been found.",
"i18n.shared.edit_allow_action_message.2000.dcat_catalog_record": "No resource has been found.",
"i18n.shared.edit_allow_action_message.2000.distribution": "No resource has been found.",
"i18n.shared.edit_allow_action_message.2000.publicservice": "No resource has been found.",
"i18n.shared.edit_allow_action_message.2003": "The resource is locked.",
"i18n.shared.edit_allow_action_message.2003.channel": "The resource is locked.",
"i18n.shared.edit_allow_action_message.2003.concept": "The resource is locked.",
"i18n.shared.edit_allow_action_message.2003.dataservice": "The resource is locked.",
"i18n.shared.edit_allow_action_message.2003.dataset": "The resource is locked.",
"i18n.shared.edit_allow_action_message.2003.dcat_catalog_record": "The resource is locked.",
"i18n.shared.edit_allow_action_message.2003.distribution": "The resource is locked.",
"i18n.shared.edit_allow_action_message.2003.publicservice": "The resource is locked.",